version: "3.4"
services:
  db:
    image: postgres:latest
    env_file: ./postgres.env
    ports:
      - "5432:5432"
    networks:
      - env-network
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file: ./postgres.env
    ports:
      - "8080:80"
    networks:
      - env-network


networks:
  env-network:
    driver: bridge

volumes:
  db-data:
    driver: local
